name: data_provider
description: Flexible data provider package
version: 0.1.7
homepage: https://github.com/DumpOfTheVar/data_provider

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  recase: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
