name: data_provider_sqlite
description: Sqlite data provider
version: 0.1.0
homepage: https://github.com/DumpOfTheVar/data_provider

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  data_provider: ^0.1.0
  path: ^1.8.3
  sqflite: ^2.2.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
