name: data_provider_sqlite
description: Sqlite data provider
version: 0.2.1
homepage: https://github.com/DumpOfTheVar/data_provider

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  data_provider: ^0.2.2
  path: ^1.8.0
  sqflite: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  mockito: ^5.3.2
  build_runner: ^2.3.3
  args: ^2.3.2
  code_builder: ^4.4.0
  analyzer: ^5.4.0
