name: data_provider_sqlite
description: Sqlite data provider
version: 0.1.1
homepage: https://github.com/DumpOfTheVar/data_provider

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  data_provider: ^0.1.3
  path: ^1.8.3
  sqflite: ^2.2.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  mockito: ^5.3.2
  build_runner: ^2.3.3
